ansible_user: ansible
ansible_password: 
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
validate_certs: false
ansible_winrm_operation_timeout_sec: 60
ansible_winrm_read_timeout_sec: 70
